# Generated by Django 5.1.1 on 2024-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('grade', models.IntegerField()),
                ('max_grade', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(related_name='users', to='account.project'),
        ),
    ]
