# Generated by Django 5.1.1 on 2024-11-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_user_projects_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usual_full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
