# Generated by Django 5.1.1 on 2024-11-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_project_user_userproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
